"""ads is_active removed_at

Revision ID: 097576a2e528
Revises: 64bfbd4df386
Create Date: 2026-08-05 19:16:07.263021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '097576a2e528'
down_revision = '64bfbd4df386'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False))
        batch_op.add_column(sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ads', schema=None) as batch_op:
        batch_op.drop_column('removed_at')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
