"""schema refactor: images, published_at, cpu structured

Revision ID: 3b94ff273458
Revises: d78937298c4a
Create Date: 2026-08-05 00:42:19.387824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b94ff273458'
down_revision = 'd78937298c4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ad_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ad_id'], ['ads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ad_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ad_images_ad_id'), ['ad_id'], unique=False)

    with op.batch_alter_table('ad_specs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cpu_family', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('cpu_model', sa.Integer(), nullable=True))
        batch_op.drop_column('year')
        batch_op.drop_column('condition')

    with op.batch_alter_table('ads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.drop_column('image_url')
        batch_op.drop_column('currency')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.VARCHAR(length=8), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=1024), nullable=True))
        batch_op.drop_column('published_at')

    with op.batch_alter_table('ad_specs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('condition', sa.VARCHAR(length=16), nullable=True))
        batch_op.add_column(sa.Column('year', sa.INTEGER(), nullable=True))
        batch_op.drop_column('cpu_model')
        batch_op.drop_column('cpu_family')

    with op.batch_alter_table('ad_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ad_images_ad_id'))

    op.drop_table('ad_images')
    # ### end Alembic commands ###
