"""initial ads table

Revision ID: 488079483ffe
Revises: 
Create Date: 2026-08-05 00:11:20.091084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '488079483ffe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('olx_id', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_cents', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('state', sa.String(length=4), nullable=True),
    sa.Column('image_url', sa.String(length=1024), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ads_url'), ['url'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ads_url'))

    op.drop_table('ads')
    # ### end Alembic commands ###
