"""cpu generation column

Revision ID: 6175a1763a42
Revises: 3b94ff273458
Create Date: 2026-08-05 01:10:47.741942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6175a1763a42'
down_revision = '3b94ff273458'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad_specs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cpu_generation', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad_specs', schema=None) as batch_op:
        batch_op.drop_column('cpu_generation')

    # ### end Alembic commands ###
